require("plugins.nvim-tree")
-- require("plugins.dracula")
require("plugins.tokyonight")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.indent-blankline")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.nvim-surround")
require("plugins.gitsigns")
require("plugins.lsp_config")
require("plugins.completions")
