require("plugins.nvim-tree")
require("plugins.vscode")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.indent-blankline")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.nvim-surround")
require("plugins.gitsigns")
require("plugins.lsp_config")
require("plugins.gitblame")
require("plugins.rust_config")
require("plugins.dap_config")
require("plugins.neodev")
-- require("plugins.completions")
-- require("plugins.dracula")
-- require("plugins.tokyonight")
