local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-f>', builtin.find_files, {})
vim.keymap.set('n', '<C-w>fg', builtin.live_grep, {})
vim.keymap.set('n', '<C-w>fb', builtin.buffers, {})
vim.keymap.set('n', '<C-w>fh', builtin.help_tags, {})
vim.keymap.set('n', '<C-w>fo', builtin.oldfiles, {})
